version: "2"
services:
  api:
    image: film-api
    container_name: film-api
    build: ./film-api
    depends_on: 
     - db
    command: yarn run start:dev
    ports:
      - 3000:3000
    volumes:
      - ./film-api:/app
      - dist:/app/dist
    environment:
      - DOCKER=true
  frontend:
    image: film_frontend
    container_name: film_frontend
    build: ./frontend
    ports:
      - 80:3000
    volumes:
      - ./frontend/:/app
      - f_front:/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
  db:
    image: mysql:5.7
    container_name: films_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: films
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
      - persistent:/var/lib/mysql
volumes:
    f_front:
    persistent:
    dist: